name: "테스트용"
on:
  push:
    branches:
      - 'master'

jobs:
  try_test:
    runs-on: ubuntu-20.04
    name: test
    steps:
      - name: Test
        run: |
          echo ${{ github.event.label.name }}
